App\Entity\Image:
  attributes:
    route_prefix: "/renarou"
  collectionOperations:
    get: ~
    post:
      security: 'is_granted("ROLE_ADMIN")'
  itemOperations:
    get: ~
    patch:
      security: 'is_granted("ROLE_ADMIN")'
    delete:
      security: 'is_granted("ROLE_ADMIN")'
